name: Systematic Wonder
favicon: null
layout_spectrum: 0.41588790086098015
typography_spectrum: 0.5090040885843337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcfcfc'
    - '#323232'
    - '#c6826a'
    - '#6f626d'
  brandStrength: 0.12203422212041914
  lightness: 0.8962748162448406
  saturation: 0.5894672486465424
  rhythmicContrast: 0.4941486590541899
purpose: []
